name: Deploy to Compute Engine

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Add execute permission to Gradle Wrapper
      run: chmod +x ./gradlew

    - name: Build project without running tests
      run: ./gradlew build -x test

    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install -y docker-ce

    - name: Install standalone Docker Compose
      run: |
        sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Build Docker images
      run: |
        docker-compose build
        docker save app | gzip > app.tar.gz
        docker save mysql | gzip > mysql.tar.gz
        docker save redis | gzip > redis.tar.gz

    - name: List generated files
      run: ls -lh *.tar.gz

    - name: Authenticate to GCP
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up GCP configuration
      run: |
        gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
        gcloud config set compute/zone ${{ secrets.GCP_ZONE }}

    - name: Transfer Docker images to VM
      run: |
        gcloud compute scp app.tar.gz mysql.tar.gz redis.tar.gz ${{ secrets.VM_NAME }}:~/ --zone ${{ secrets.GCP_ZONE }}

    - name: Load Docker images on VM and start services
      run: |
        gcloud compute ssh ${{ secrets.VM_NAME }} --zone ${{ secrets.GCP_ZONE }} --command "
          gunzip -c app.tar.gz | sudo docker load &&
          gunzip -c mysql.tar.gz | sudo docker load &&
          gunzip -c redis.tar.gz | sudo docker load &&
          sudo docker-compose up -d
        "
