name: Deploy to Compute Engine

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '21'

    - name: Build project with Gradle
      run: ./gradlew build

    - name: Build Docker images
      run: |
        docker-compose build
        docker save app | gzip > app.tar.gz
        docker save mysql | gzip > mysql.tar.gz
        docker save redis | gzip > redis.tar.gz

    - name: Deploy to Compute Engine
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Transfer Docker images to VM
      run: |
        gcloud compute scp app.tar.gz mysql.tar.gz redis.tar.gz [VM_NAME]:~/ --zone [ZONE]

    - name: Load Docker images on VM and start services
      run: |
        gcloud compute ssh [VM_NAME] --zone [ZONE] --command "
          gunzip < app.tar.gz | docker load &&
          gunzip < mysql.tar.gz | docker load &&
          gunzip < redis.tar.gz | docker load &&
          docker-compose up -d
        "
